version: "3.8"
services:
  app:
    image: mcr.microsoft.com/devcontainers/typescript-node:1-22-bullseye
    command: sleep infinity
    volumes:
      - ..:/workspaces:cached
    networks:
      - default
    depends_on:
      - pgapp
      - redis
      - temporal
      - temporal-ui

  pgapp:
    image: postgres:16
    environment:
      POSTGRES_DB: catalyst
      POSTGRES_USER: catalyst
      POSTGRES_PASSWORD: catalyst
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  temporal:
    image: temporalio/auto-setup:1.23
    depends_on:
      - pgapp
    environment:
      DB: postgresql
      DB_HOST: pgapp
      DB_PORT: "5432"
      DB_USER: catalyst
      DB_PASSWORD: catalyst
      DB_NAME: catalyst
    ports:
      - "7233:7233"

  temporal-ui:
    image: temporalio/ui:latest
    depends_on:
      - temporal
    environment:
      TEMPORAL_ADDRESS: temporal:7233
    ports:
      - "8080:8080"

networks:
  default:
    name: devcontainer_default
