version: "3.8"
services:
  app:
    image: mcr.microsoft.com/devcontainers/typescript-node:1-22-bullseye
    command: sleep infinity
    volumes:
      - ..:/workspaces:cached
    networks:
      - default
    # Uncomment and use only when needed
    # depends_on:
    #   - pg
    #   - redis
    #   - temporal
    #   - temporal-ui
    # ports:
    #   - "3000:3000"

  # Optional local infra (disabled until used)
  # pg:
  #   image: postgres:16
  #   environment:
  #     POSTGRES_USER: dev
  #     POSTGRES_PASSWORD: dev
  #     POSTGRES_DB: devdb
  #   ports:
  #     - "5432:5432"

  # redis:
  #   image: redis:7
  #   ports:
  #     - "6379:6379"

  # temporal:
  #   image: temporalio/auto-setup:1.24
  #   environment:
  #     - DB=postgresql
  #   ports:
  #     - "7233:7233"

  # temporal-ui:
  #   image: temporalio/ui:latest
  #   environment:
  #     - TEMPORAL_ADDRESS=temporal:7233
  #   ports:
  #     - "8080:8080"

networks:
  default:
    name: devcontainer_default
