version: "3.8"
services:
  app:
    image: mcr.microsoft.com/devcontainers/typescript-node:1-22-bullseye
    volumes:
      - ..:/workspaces/${COMPOSE_PROJECT_NAME}:cached
    command: sleep infinity
    depends_on:
      - pgapp
      - redis
      - temporal
      - temporal-ui
  pgapp:
    image: postgres:16
    environment:
      POSTGRES_USER: catalyst
      POSTGRES_PASSWORD: catalyst
      POSTGRES_DB: catalyst
    ports:
      - "5432:5432"
  redis:
    image: redis:7
    ports:
      - "6379:6379"
  temporal:
    image: temporalio/auto-setup:1.23
    environment:
      - DB=postgresql
      - DB_HOST=pgapp
      - DB_PORT=5432
      - DB_USER=catalyst
      - DB_PASSWORD=catalyst
      - DB_NAME=catalyst
    ports:
      - "7233:7233"
    depends_on:
      - pgapp
  temporal-ui:
    image: temporalio/ui:2.28
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
    ports:
      - "8080:8080"
    depends_on:
      - temporal
